export default {
    signUp: `//a[contains(text(),'Sign up')]`,
    logIn: `//a[contains(text(),'Login')]`,
    btnLogin: `//button[contains(text(),'Login')]`,
    btnCreateAccount: `//button[contains(text(),'Create an account')]`,
    btnContinue: `//button[contains(text(),'Continue')]`,
    btnConnect: `//button[contains(text(),'Connect')]`,
    modalSignUp: `.modal-signup.ng-scope`,
    txtEmailPhone: `#signup_emailOrPhone`,
    txtLoginEmailPhone: `#login_emailOrCellPhone`,
    txtPassword: `#signup_password`,
    txtLoginPassword: `//input[@type='password']`,
    chkNonProfit: `//span[contains(text(),'I work at a nonprofit')]`, // unnecessary?
    chkBox: `//input[@type="checkbox"]`, // generic
    txtLocationSetters: `*[id*="location_setter"]`,
    langEnglish: `//label[value="en"]`,
    langSpanish: `//label[value="es"]`,
    txtFirstName: `//input[@placeholder='First name' and @aria-hidden='false']`,
    txtLastName: `//input[@placeholder='Last name' and @aria-hidden='false']`,
    txtOrg: `#org-search_value`,
    txtPosition: `//input[@placeholder="Position" and @aria-hidden="false"]`,
    txtPhone: `//input[@placeholder='Cell phone' and @aria-hidden='false']`, // `input[ui-mask="999-999-9999"]`,
    ddDOBDay: `//button[contains(text(),'Day')]`,
    ddDOBMonth: `//button[contains(text(),'Month')]`,
    ddDOBYear: `//button[contains(text(),'Year')]`,
    ddArray: `//ul[@class='dropdown-menu']`, // [1] = Day, [2] = Month, [3] = Year
    // smallMenuBtn: `//a[@class='btn']`,
    menuBtn: `div.main-menu.nav-dropdown-menu a`,
    smallMenuBtn: `i.fa-fw.fa-bars`,
    smallLocation: `//li/a[@ng-click='openLocationModal()']`,
    defaultLocationBtn: `//button[@ng-click='openUpdateRegionModal()']`,
    locationSetter: `input[id^=location_setter]`,
    smallAssessments: `//a[@href='/plan#assessments' and @ng-click='toggleSideBar()']`,
    smallSignUp: `//a[@ng-click='openSignupModal(); toggleSideBar()']`,
    smallLogin: `//a[@ng-click='openLoginModal(); toggleSideBar()']`,
    smallDismissApp: `//i[@class="fa fa-w fa-close"]`,
    defaultNavBar: `//div[@class='col-sm-12 area-tabs']`,
    defaultRegionBtn: `//button[@ng-click='openUpdateRegionModal()']`,
    loading: `//div[@class="cg-busy cg-busy-animation ng-scope"]`,
    spinner: `.spinner`,
    successAlert: `//button[@ng-show='closeable']`,
    close: `//button[@class='close']`,
}